M48
; DRILL file {KiCad 8.0.2-8.0.2-0~ubuntu22.04.1} date 2024-05-15T17:42:07+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-15T17:42:07+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-8.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
%
G90
G05
T1
X3.7008Y-3.4449
X4.5276Y-3.4449
M30
